CC=g++
CFLAGS=-std=c++17 -march=native -Wall -O3 -o "Versions/Leandor 2.2 gcc v0.exe"

engine: main.cpp bitboard.cpp attacks.cpp search.cpp movegen.cpp evaluator.cpp board_state.cpp bit_move.cpp magics.cpp movelist.cpp perft.cpp scorelist.cpp transposition_table.cpp tt_entry.cpp uci_io.cpp utility.cpp
	$(CC) $(CFLAGS) main.cpp bitboard.cpp attacks.cpp search.cpp movegen.cpp evaluator.cpp board_state.cpp bit_move.cpp magics.cpp movelist.cpp perft.cpp scorelist.cpp transposition_table.cpp tt_entry.cpp uci_io.cpp utility.cpp
